apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ubuntu
  template:
    metadata:
      labels:
        app: my-ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          imagePullPolicy: Always
          command:
            - sleep
            - "3800"