name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run invoke coverage

      - name: Coverage report
        run: poetry run coverage xml

      - name: Pylint
        run: poetry run invoke lint --backend

      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

      - name: List repo files (debug)
        run: |
          echo "Repo root: $(pwd)"
          ls -la
          echo "--- recursive listing ---"
          ls -laR

      - uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      # Debug: show the tags we'll use (non-secret)
      - name: Debug show tags
        run: |
          echo "Backend tags: ${DOCKER_REGISTRY}/${DOCKER_USER}/walkamile-backend:staging, ${DOCKER_REGISTRY}/${DOCKER_USER}/walkamile-backend:${GITHUB_SHA}"
          echo "Frontend tags: ${DOCKER_REGISTRY}/${DOCKER_USER}/walkamile-frontend:staging, ${DOCKER_REGISTRY}/${DOCKER_USER}/walkamile-frontend:${GITHUB_SHA}"

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USER }}/walkamile-backend:staging
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USER }}/walkamile-backend:${{ github.sha }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USER }}/walkamile-frontend:staging
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USER }}/walkamile-frontend:${{ github.sha }}
