name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Single checkout only
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run invoke coverage

      - name: Coverage report
        run: poetry run coverage xml
      
      - name: Pylint
        run: poetry run invoke lint --backend

      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

      # Debug: show repo files so we can confirm Dockerfiles exist and paths
      - name: List repo files (debug)
        run: |
          echo "Repo root: $(pwd)"
          ls -la
          echo "--- recursive listing ---"
          ls -laR

      # Docker build steps (no second checkout)
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: walkamile
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: .                 # build context = repo root
          file: Dockerfile          # path to Dockerfile relative to context
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/walkamile-backend:latest,${{ secrets.DOCKER_USERNAME }}/walkamile-backend:${{ github.sha }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .                 # if frontend files are under ./frontend change this
          file: Dockerfile.frontend  # path relative to context; change if file is elsewhere
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/walkamile-frontend:latest,${{ secrets.DOCKER_USERNAME }}/walkamile-frontend:${{ github.sha }}
