name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run invoke coverage

      - name: Coverage report
        run: poetry run coverage xml
      
      - name: Pylint
        run: poetry run invoke lint --backend

      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

      - name: Login to Docker Hub
        uses: docker/logi-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{secrets.DOCKER_PASSWORD }}

      - name: Set up QeMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-and-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: {{ secrets.DOCKER_USERNAME }}/walkamile-backend:latest
        
      - name Build and push frontend
        uses: docker/build-and-push-action@v6
        with:
        context: .
          file: ./Dockerfile.frontend
          push: true
          tags: {{ secrets.DOCKER_USERNAME }}/walkamile-frontend:latest
