name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      TEST_ENV: "true"  # Set TEST_ENV to true for the test environment

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run invoke coverage

      - name: Coverage report
        run: poetry run coverage xml
      
      - name: Pylint
        run: poetry run invoke lint --backend

      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v5
